import Head from 'next/head';
import Link from 'next/link';
import Logo from '@/components/Logo/Logo';
import Login from '@/components/Login/Login';


export default function Home() {

  return (
    <>
      <Head>
        <title>Easy Marry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="page-landing">
        <header>
          <Logo />        
        </header>
        <div className="title-container">
          <h1>
            Assim começa uma nova <span>História</span>
          </h1>
        </div>
        <main className='page-home'>
          <h1>Entre em sua conta</h1>
          <div className="container-register">
            <p>Não tem uma conta? <Link href='/typeselection'>Clique Aqui!</Link></p>
            {/* <p>Lista de Fornecedores <Link href='/supplier/suppliers'>Clique Aqui!</Link></p> */}
            <Login />
           
          </div>
        </main>
      </div>
      
    </>
  )
}
