import Posts from "@/components/Posts/posts";
import Head from "next/head";

export default function Supplier(){
    return(
    <>
    <Head>
                <title>Easy Marry</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <main className="resultSupplier">
        <div className="container-result">
            <Posts />
        </div>
    </main>
    </>
    );
}