import Head from 'next/head'
import Image from 'next/image'
import {LOGOIMAGE} from '../utils/Patys'
import Logo from '@/components/Logo/Logo'
import Login from '@/components/Login/Login'


export default function Home() {

  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <div className="page-landing">
        <header>
          <Logo />        
        </header>
        <div className="container-title">
            <h1>Assim <br/> começa <br /> uma nova <br/><span>História</span></h1>
        </div>
        <main>
          <h1>Entre em sua conta</h1>
          <div className="container-form">
            <p>Não tem uma conta? <a href="#">Clique aqui!</a></p>
            <Login />          
            <p><a href='#'>Você é fornecedor</a></p>
            <p><a href='#'>Acesso para fornecedores</a></p>
          </div>
         
        </main>
      </div>
      
    </>
  )
}
