import Logo from "@/components/Logo/Logo";
import Head from "next/head";

export default function SupplierRegistration(){
    return (
       <>
            <Head>
                <title>Easy Marry</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <header>
                <Logo/>
            </header>
       </> 
    );
}